# typed: false
# frozen_string_literal: true

# Formula generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Orchestrator < Formula
  desc "AI-native SDLC automation — agent orchestrator CLI and daemon"
  homepage "https://github.com/c9r-io/orchestrator"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "6b252b7171f9a150fc1d194188db00244a43df1b27c8fcea1cc0780de945dd02"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a36c84db6b752e4639ea3ca0bc4df45e0f711fd9b2102d98fa4a8ba5ccf808cf"
    end
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6d4067cf322fab2871671dabc836a69f9563ad0aa559276877023d92849acac7"
    end
  end

  def install
    bin.install "orchestrator"
    bin.install "orchestratord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/orchestrator --version")
  end
end
