# typed: false
# frozen_string_literal: true

# Formula generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Orchestrator < Formula
  desc "AI-native SDLC automation — agent orchestrator CLI and daemon"
  homepage "https://github.com/c9r-io/orchestrator"
  version "0.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.4/orchestrator-v0.2.4-aarch64-apple-darwin.tar.gz"
      sha256 "a920f4a3e4438373e938c5937ab1f07ece57c1f67d2b048f2e13b26651ea6d5a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.4/orchestrator-v0.2.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "50fb9f5769362a9459a64388e2e0d997cf91d99fdc84b9065428845ea0bd523f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.4/orchestrator-v0.2.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2cc5f87d972cdf90e838f9437b397923dbb7917b8e8e63e78cfccb5c714d36ac"
    end
  end

  def install
    bin.install "orchestrator"
    bin.install "orchestratord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/orchestrator --version")
  end
end
