# typed: false
# frozen_string_literal: true

# Formula generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Orchestrator < Formula
  desc "AI-native SDLC automation — agent orchestrator CLI and daemon"
  homepage "https://github.com/c9r-io/orchestrator"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "7e301785210eb04f18359e58a4bf253af81d10f8293d038e038e0db6453e5cd5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2804b59ade13b2e5339c899c9d76937d01b3e933a06c8a3738aa8e2dafb9974e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/c9r-io/orchestrator/releases/download/v0.2.3/orchestrator-v0.2.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bd5f6f55282840c834754a64f468c527778fc9a4e69cda8740bc3742625c8712"
    end
  end

  def install
    bin.install "orchestrator"
    bin.install "orchestratord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/orchestrator --version")
  end
end
